### ISSUE TITLE
HTTP POST on Xbee Python

### ISSUE THREAD

**Issue by danieljoserm** [digidotcom/xbee-python#127]
Hello, I would like to know if there is any method on the Xbee Python library for sending HTTP post request to a web server from the Xbee Cellular modem https://www.digi.com/products/embedded-systems/digi-xbee/cellular-modems/xbee3-cellular-lte-m-nb-iot

**Comment by brandonmoser** [comment]
@danieljoserm Please check out the MicroPython documentation which relates to the development environment on the XBee3 Cellular modules. https://www.digi.com/resources/documentation/digidocs/90002219/default.htm

**Comment by craftyshark** [comment]
@brandonmoser there is nothing there on POST requests from what I could see
