### ISSUE TITLE
ImportError: No module named 'digi'

### ISSUE THREAD

**Issue by pablovi96** [digidotcom/xbee-python#166]
Hi,
I try to communicate between a ccimx6ulsbc board with yocto and a xbee zigbee device. I run a python script in which I do the following:
```
from digi.xbee.devices import ZigBeeDevice, RemoteZigBeeDevice, XBee64BitAddress
			xbee = ZigBeeDevice("/dev/ttyXBee", 9600)
			xbee.open()
			remote = RemoteZigBeeDevice(xbee, XBee64BitAddress.from_hex_string(mac))
			xbee.send_expl_data(remote, message, se, de, clid, prfid)
			xbee.close()
```
		
but then it fails with this error:

```
Traceback (most recent call last):
  File "/etc/init.d/udp.py", line 6, in <module>
    from digi.xbee.devices import ZigBeeDevice, RemoteZigBeeDevice, XBee64BitAddress
ImportError: No module named 'digi'
```
Why does this happen? 
Last time, when I booted via tftp I didnt have this problem but now I boot from sd card yes.

**Comment by daescalona** [comment]
Hello @pablovi96 ,

It seems that you do not have the XBee Python Library installed in the ccimx6ulsbc. You may need to either compile DEY images adding the "python3-xbee" recipe to it or install the XBee Python library from the ccimx6ulsbc using "pip install xbee-python".

Kind regards.
