### ISSUE TITLE
How do I discover the mac address of the devices in my zigbee network?

### ISSUE THREAD

**Issue by pablovi96** [digidotcom/xbee-python#167]
Im using the get_network() and get_devices() function and I discover the devices but I dont get its mac address. Is there any function that returns all the mac addresses of the devices in the zigbee network?

**Comment by rubenmoral** [comment]
Hi @pablovi96,

Here you have the documentation that explains how to discover a network and retrieve the remote nodes: https://xbplib.readthedocs.io/en/latest/user_doc/discovering_the_xbee_network.html#discover-the-network. Once you have the list of devices, you can iterate over it and call the `get_64bit_addr()` method for each `RemoteXBeeDevice` object to get its MAC address.

BTW, the purpose of the GitHub issue tracker is to report issues, not for help requests. For this type of questions, please go to the [Digi Forum](http://cms.digi.com/support/forum/) or contact tech.support@digi.com.

Best regards.
