### ISSUE TITLE
XBeeNetwork.__last_search_dev_list grows infinitely

### ISSUE THREAD

**Issue by Eric-Levine** [digidotcom/xbee-python#172]
Every time the discovery process finds a node (including a node that has already been seen), it adds that node to the __last_search_dev_list [(code)](https://github.com/digidotcom/xbee-python/blob/master/digi/xbee/devices.py#L8718).

The list is never emptied or maintained, and appears to only be used in one place [(code)](https://github.com/digidotcom/xbee-python/blob/master/digi/xbee/devices.py#L7748).

I'm not entirely sure what the goal of the list is, but at a guess based on naming, it seems to be a list that should reflect nodes discovered during the last node discovery process. If that's correct, this problem could be resolved by clearing the list when node discovery is started.

A potential stopgap that I have yet to test is just manually emptying the list before starting discovery

My use case is long-running service on an embedded system where the discovery process is running constantly (XBeeNetwork.start_discovery_process() is called at the end of my discovery process finished callback). I'm using XBee Pro S3B modules in API mode with escapes.

**Comment by tatianaleon** [comment]
Hi @Eric-Levine,

Thanks for reporting this issue. We have just fixed it in `master` (see commit https://github.com/digidotcom/xbee-python/commit/96886886d101222e2bb8792e181aadb64fa22eca) and will be included in the next release.

In the meantime, you can download the source code from the master branch and install the library from there (see instructions at https://github.com/digidotcom/python-xbee/blob/master/README.rst#install-from-source).

Sorry for the inconvenience.

Best regards.
