### ISSUE TITLE
SPI support on xbee-python

### ISSUE THREAD

**Issue by UTSAnonymous** [digidotcom/xbee-python#180]
Hi, 

From what I saw my XBee S2c Pro supports SPI, however looking at the documentation for the xbee-python library it doesn't mention that SPI is supported.

Is there anyway to enable SPI support for the Xbee-python library?

**Comment by ahmetakman** [comment]
I am also quite interested in that issue.

**Comment by tatianaleon** [comment]
Hi @UTSAnonymous and @ahmetakman,

I'm afraid, the library only communicates with local XBee nodes connected via a serial port. It does not include SPI support to connect with local XBee radios.

Best Regards.
