### ISSUE TITLE
Get state of zigbee device

### ISSUE THREAD

**Issue by sami-baroudi** [digidotcom/xbee-python#188]
Hi,

I'm using the xbee-python library to control an OSRAM Smart +. So far, I can control the light bulb parameters ( On/Off, brightness and Temperature) by deducing the frame structure and send it using the send_explicit_data method. I'm curious to know if there is a way to get the light bulb state  (On/Off, brightness value and Temperature value) by sending a specific payload and using the read_explicit_data after.

Regarding this method, I wanted to know if this method send a request before reading or it reads only incoming data on the module?

When sending the a payload (On/off, etc..) I get a packet while using read_explicit_data just right after. But when analyzing the payload received, nothing interesting...

**Comment by tatianaleon** [comment]
Hi @sami-baroudi,

I guess there will be a way to get the light bulb state by sending an explicit data frame to the right profile, cluster id, and end points. You must consult the corresponding Zigbee profile (maybe Zigbee Light Link) to know the capabilities of your bulb.

Regarding the method `read_expl_data` it does not send anything, it just wait for explicit data coming from any node in the network.

Best Regards.
