### ISSUE TITLE
XBee Pro S3B InvalidOperatingModeException Error

### ISSUE THREAD

**Issue by brettv30** [digidotcom/xbee-python#190]
I'm attempting to use the SendDataSample.py file with two XBee Pro S3B modules. I have tried having each module in different modes (AT, API1, API2) and nothing seems to be working. I keep getting, InvalidOperatingModeException as an error. When I go into XCTU I can see that both modules are connected to one another in a network so i'm not sure what the problem would be. Any help is appreciated, thanks!

**Comment by brandonmoser** [comment]
@brettv30 Please post a code example of how you are trying to communicate to each module.
