### ISSUE TITLE
Broadcast Message Failing to Send 

### ISSUE THREAD

**Issue by GriffinMack** [digidotcom/xbee-python#200]
Hello, 

I am trying to send a broadcast message but the message keeps failing. The exact stack trace can be found below. The json string I am trying to send is also found below. If I shorten this string, the message sends successfully. However, I am within the 256 byte limit for my xbee device with this string, so I can't see why this would be the reason for failure.

Exact Message(String):
"{"In Air": false, "Is Armed": false, "Satellites Discovered": 10, "Fix Type": "FIX_3D", "Battery Percentage": -0.01, "Flight Mode": "LAND"}"

Trace:
  File "/Users/griffinmack/.pyenv/versions/3.8.1/lib/python3.8/site-packages/digi/xbee/devices.py", line 2576, in send_data_broadcast
    return self._send_data_64(XBee64BitAddress.BROADCAST_ADDRESS, data,
  File "/Users/griffinmack/.pyenv/versions/3.8.1/lib/python3.8/site-packages/digi/xbee/devices.py", line 1584, in dec_function
    return func(self, *args, **kwargs)
  File "/Users/griffinmack/.pyenv/versions/3.8.1/lib/python3.8/site-packages/digi/xbee/devices.py", line 1597, in dec_function
    raise TransmitException(transmit_status=response.transmit_status)
digi.xbee.exception.TransmitException: There was a problem with a transmitted packet response (status not ok)

**Comment by tatianaleon** [comment]
Hello @GriffinMack,

The maximum payload size for broadcast transmissions is less than the maximum payload size for unicast transmissions.
For non-encrypted transmissions in a Zigbee network, a broadcast message can have a maximum of 92 bytes.
That is, your message above (139 bytes) can be "unicasted" but not "broadcasted".

Best Regards.
