### ISSUE TITLE
New release and changelog

### ISSUE THREAD

**Issue by FRVisser** [digidotcom/xbee-python#209]
Hello Digi, 

The library has seen a lot of commits in 2020. It seems good to release a new (sub)version and update the changelog. As the 'summer update' as mentioned in our calls is not seen back in the releases.

Thanks,
Fokko

**Comment by duysqubix** [comment]
bumping this - I haven't noticed the massive amounts of commits since 1.3.0. Was tracking down something only to discover src from 1.3.0 is vastly different

**Comment by duysqubix** [comment]
@brandonmoser who can we tag to get this issue some attention? I am about at the point to fork this project and create my own release to upload to pip so I can use in projects instead of pulling from git directly.

**Comment by FRVisser** [comment]
I'll also send I mail to my contact at Digi

**Comment by brandonmoser** [comment]
Any support request should go to Tech.Support@digi.com <mailto:Tech.Support@digi.com>.


--
Brandon Moser

**Comment by duysqubix** [comment]
@brandonmoser who is the owner of this repo?

**Comment by brandonmoser** [comment]
Digi International (https://www.digi.com/ <https://www.digi.com/>) is the owner. One of the engineering teams supports the project.

--
Brandon Moser
brandon@brandonmoser.com

**Comment by duysqubix** [comment]
@brandonmoser is there a direct contact for one of the engineering team members? Whether via git or email?

**Comment by tatianaleon** [comment]
Hi @FRVisser,

Version 1.4.0 is released and available in PyPI: https://pypi.org/project/digi-xbee/1.4.0/

Best Regards
