### ISSUE TITLE
Installation from source enhancement

### ISSUE THREAD

**Issue by klosiu** [digidotcom/xbee-python#226]
Since the project uses native namespace packaging, installing by:
`$ python setup.py install`
doesn't work as expected. 
It seems, that a package without an `__init__.py` file can't be found inside the resulting .egg file, when importing modules, resulting in `ModuleNotFoundError`.

As a workaround a flag `zip_safe = False` can be added to setup.py:
```
    setup(
    zip_safe = False,  
    name=about['__title__'],  
    namespace_packages=['digi'],
    ...
```
or the `Install from Source` instruction inside the readme file may be changed to:
`$ pip install .`

It's quite relevant as there have been dozens of commits made to master since the last release, and the latest one doesn't work in Python 3.9 due to #204.

I tested that on Manjaro, Python 3.9.1, setuptools 49.2.1 and pip 21.0.1

**Comment by tatianaleon** [comment]
Hi @klosiu,

Version 1.4.0 is released and available in PyPI: https://pypi.org/project/digi-xbee/1.4.0/

The instructions to install from sources in the README are updated to use `pip`.

Thank you.
