### ISSUE TITLE
Error with import modules

### ISSUE THREAD

**Issue by mohamadnoor991** [digidotcom/xbee-python#237]
Hello, i am working on Xbee3 with XBee grove.
When I am open the microphone terminal and trying to execute code the error  "ImportError: no module named 'UART'"
AND ALOT OF LIKE THIS error.
the pip is not working inside the Xbee Micropython terminal.
i don't know how I can install this module in xbee3
Anyone can help me, please

**Comment by tatianaleon** [comment]
Hi @mohamadnoor991,

This is a Python library that cannot run inside and XBee 3.
XBee 3 runs MicroPython and pip is not working there. Please refer to the [Digi MicroPython Guide](https://www.digi.com/resources/documentation/digidocs/90002219/default.htm) to know what is available. 

Best Regards

**Comment by mohamadnoor991** [comment]
ok that is clear but how i can install the missing module in xbee3 like "UART and digi" ?
i need these modules to start programming and execute my ideas

**Comment by tatianaleon** [comment]
Hi @mohamadnoor991,

As far as I know, you cannot install new modules on a XBee 3. Inside the [Digi MicroPython Guide](https://www.digi.com/resources/documentation/digidocs/90002219/default.htm) you can check what is available.

Anyway, the right place to ask about MicroPython on a XBee 3 is https://github.com/digidotcom/xbee-micropython.

Best Regards.

**Comment by mohamadnoor991** [comment]
Dear @tatianaleon  thanks for your answer
