### ISSUE TITLE
except TimeoutException, ex:

### ISSUE THREAD

**Issue by bocephasj** [digidotcom/xbee-python#286]
I am getting a syntax error - except TimeoutException, ex: - python 3.9 says syntax error @ comma in this statement in base.py of xbee library.
Does anyone know why?

# ignore timeouts, but this allows the thread to be responsive rather
            # than blocking indefinitely on read
            except TimeoutException, ex:
                if ex.args: log.debug("Packet timeout after %s bytes", ex)

**Comment by tatianaleon** [comment]
Hi @bocephasj,

[base.py](https://github.com/digidotcom/xbee-python/blob/master/digi/xbee/packets/base.py) does not include any code similar to that.
If this is your code, use parenthesis for multiple exceptions or remove the comma for a single exception and `as` word to assign the exception to a variable:
```python
    try:
        [...]
    except TimeoutException as ex:
        print(ex)
```  
See https://docs.python.org/3.9/tutorial/errors.html#handling-exceptions and https://docs.python.org/3.9/reference/compound_stmts.html#except
