### ISSUE TITLE
Reading sensor data using SMT development board

### ISSUE THREAD

**Issue by sayaz** [digidotcom/xbee-python#299]
Hi, I am using an XBee SMT grove development board (on 802.15.4), connected with grove temperature sensor (BME680). As the below figure:

![IMG_1825](https://github.com/digidotcom/xbee-python/assets/22035469/387863bd-ee4a-4a32-b635-8ae4eb02bc1f)

Now I just want to read the temperature values using Python. Is there any example code available ??

**Comment by sayaz** [comment]
I am using the below code but it is not giving any output on temperature:

```
from digi.xbee.io import IOLine, IOMode
from digi.xbee.devices import XBeeDevice

PORT = "/dev/tty.usbserial-AB0OPD7U"
BAUD_RATE = 9600

IOLINE_IN = IOLine.DIO1_AD1

def main():
    print(" +----------------------------------------+")
    print(" | Read IO sample test |")
    print(" +----------------------------------------+\n")

    xbee = XBeeDevice(PORT, BAUD_RATE)

    xbee.open()

    xbee.set_io_configuration(IOLine.DIO1_AD1, IOMode.DIGITAL_IN)

    sample = xbee.read_io_sample()
    assert (sample.has_digital_value(IOLine.DIO1_AD1))
    
    print(sample)

if __name__ == '__main__':
    main()
```
Output
`{[IOLine.DIO1_AD1: IOValue.HIGH], [IOLine.DIO4_AD4: IOValue.LOW]}`

**Comment by rubenmoral** [comment]
Hi @sayaz,

As stated in the [CONTRIBUTING](https://github.com/digidotcom/xbee-python/blob/master/CONTRIBUTING.rst) file, the GitHub issue tracker is to report bugs in the library. Requests for help and questions should be asked using the [Digi Forum](https://forums.digi.com/).
