### ISSUE TITLE
send source route frame

### ISSUE THREAD

**Issue by mbPejvak** [digidotcom/xbee-python#54]
I create source route frame data structure as a string (the sequence of data explained in XBee manual) in python and I need to send it to xbee module through UART. I do not know how to do it, which class or function in XBee python library can perform it.

**Comment by orenbell-nidec** [comment]
I'm guessing you're interested in the RouteInfoPacket type. This isn't implemented in the official API, but I wrote a patch to add it in, if it helps. 
[routeinfo.zip](https://github.com/digidotcom/python-xbee/files/3315805/routeinfo.zip)

**Comment by tatianaleon** [comment]
Hi @mbPejvak,

In `master` we already included the method `get_route_to_node()` to get the route to a node.

```python
xbee = ZigBeeDevice(PORT, BAUDRATE)
xbee.open()

[...]

remote = RemoteZigBeeDevice(xbee, x64bit_addr=XBee64BitAddress.from_hex_string("1234567890ABCDEF"))

status, route = xbee.get_route_to_node(remote, timeout=5)
print("Transmit status: %s (%d)" % (status.description, status.code))
print("Route source: %s" % route[0])
print("Route destination: %s" % route[1])
print("Route hops (closest to src to closest to dst): %s"
          % " <<< ".join(map(str, route[2])))

[...]
```

It is also possible to register a callback to listen for received routes with `add_route_received_callback()` and remove it with `del_route_received_callback()`.
The callback receives 3 parameters: source node, destination node, and the list of hops from closest to source to closest to destination:

```python
xbee = ZigBeeDevice(PORT, BAUDRATE)
xbee.open()

[...]

def new_route_cb(src, dest, hops):
    print("Received route: %s%s%s <<< %s (hops: %d)"
          % (dest, " <<< " if hops else "", " <<< ".join(map(str, hops)),
             src, (len(hops) + 1)))

xbee.add_route_received_callback(new_route_cb)

[...]

xbee.del_route_received_callback(new_route_cb)

[...]
```

This support will be released in the next version. In the meantime, you can download the source code from the master branch and install the library from there (see instructions at https://github.com/digidotcom/python-xbee/blob/master/README.rst#install-from-source).

Best Regards.
