### ISSUE TITLE
Installing into a python3 virtualenv 

### ISSUE THREAD

**Issue by legend-patrick** [digidotcom/xbee-python#58]
Hi all,
Love this library, thank you.

I setup a python virtual environment running v3.5.3.  When I run pip to install the library, it still errors with python version must be v3.  My system level python install is 2.7.  I am running debian 9 and when I check the python version in the virtualenv, it does come up as 3.5.3.

Thank you very much

**Comment by FRVisser** [comment]
Did you try running it with `pip3` instead of `pip`?

**Comment by brandonmoser** [comment]
@legend-patrick were you able to get this to work? What OS are you running this on?
