### ISSUE TITLE
This code works with Xbee S2 in API mode, but when i tried it between two Xbee S2B, it couldnot discover the node.

### ISSUE THREAD

**Issue by mchaudh4** [digidotcom/xbee-python#64]
This code works with Xbee S2 in API mode, but when i tried it between two Xbee S2B, it couldnot discover the node.

**Comment by tatianaleon** [comment]
Hi @mchaudh4,

We would need the error you are getting, details of your hardware and setup, and a piece of example code to reproduce the issue.

Best Regards

**Comment by mchaudh4** [comment]
Hi tatianleon, It is more than a year now from when i created the issue. I managed some more Xbee S2, finished my thesis  and completed my graduation. Thank you for your kind help.
