### ISSUE TITLE
I am not able to make a receiver and transmitter together in the same code. The program gets stuck at receiver code indefinitely?

### ISSUE THREAD

**Issue by mchaudh4** [digidotcom/xbee-python#67]

**Comment by tatianaleon** [comment]
Hello @mchaudh4,

We would need a piece of code to reproduce the issue.

Best Regards.

**Comment by mchaudh4** [comment]
Hi Tatianaleon, This error was just because of the error in my python script. There is absolutely no problem in your Library.
