### ISSUE TITLE
IS Command Response parsing is wrong (Data part)

### ISSUE THREAD

**Issue by b33fjerky** [digidotcom/xbee-python#90]
Sending IS command via XCTU has a correctly parsed response from the remote module:
![Screen Shot 2019-09-17 at 07 11 29](https://user-images.githubusercontent.com/54108262/65010983-7366ba00-d91a-11e9-8652-a4c768526356.png)

However issuing `print(remote_xbee.get_parameter('IS'))` seems the data part is parsed incorrectly containing illegal characters etc:
![Screen Shot 2019-09-17 at 05 16 51](https://user-images.githubusercontent.com/54108262/65011033-aad56680-d91a-11e9-9447-a96684241682.png)

**Comment by tatianaleon** [comment]
Hi @b33fjerky 

When you print out a byte array in the way you are doing, python will show the equivalent ASCII character if it is printable. In your case the `;` is the printable char of the code `0x3B` and the `\x017` is equivalent to `0x01 0x37`.
Show your bytearray:
`b'\x01\x88\xd0\x0f\x08\xd0\x01;\x00\x12\x017\x017'`
is the equivalent to
`01 88 D0 0F 08 D0 01 3B  00 12 01 37 01 37`

If you want to print out something like this, you can use the function
```python
digi.xbee.util.utils.hex_to_string(your_byte_array, pretty=True)
```

Best Regards.
