### ISSUE TITLE
Setting AP mode via set_parameter("AP",    )

### ISSUE THREAD

**Issue by b33fjerky** [digidotcom/xbee-python#94]
Documentation says expected values are  ("AP", 0) ("AP", 1) ("AP", 2)
I think there should be a snippet of code showing that it only works as:
set_parameter("AP", bytearray("\x00","utf8"))
set_parameter("AP", bytearray("\x01","utf8"))
set_parameter("AP", bytearray("\x02","utf8"))

**Comment by tatianaleon** [comment]
Hi @b33fjerky ,

If you could point us where the documentation of the library mention that, we will update it.
The method `set_parameter()` uses a string for the setting to configure and a bytearrary for its value, as it is documented at https://xbplib.readthedocs.io/en/latest/user_doc/configuring_the_xbee_device.html#set-a-parameter

Best Regards.
