### ISSUE TITLE
Discovery not working

### ISSUE THREAD

**Issue by Aydin2** [digidotcom/xbee-python#97]
Discovery example only prints the coordinator address. 
Coordinator is S2C, API 2
XCTU finds the endpoint device

**Comment by securitybryan** [comment]
Could you post a code snippet so we can gain more insight into what you are doing?

**Comment by sami-baroudi** [comment]
Hello,
I'm facing the same error:
I'm using a S2C in Coordinator mode + API2.
When launching the discovery, it returns an empty list. But XCTU detects the other device.

Code snippet :
![Screenshot from 2020-07-02 09-56-21](https://user-images.githubusercontent.com/56584664/86332141-65381f00-bc4a-11ea-9b0b-f0503d0eadef.png)

**Comment by securitybryan** [comment]
Have you tried bumping up the timeout value?   It is not uncommon for me to see 8-10 seconds for scan results.  I would set it to 25 for testing and then bump down from there.

**Comment by tatianaleon** [comment]
@sami-baroudi, please see https://github.com/digidotcom/xbee-python/issues/184#issuecomment-653629609
